//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem_DatabaseOperation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPSystemTaskEntities : DbContext
    {
        public ERPSystemTaskEntities()
            : base("name=ERPSystemTaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblStudent_details> tblStudent_details { get; set; }
        public virtual DbSet<tblStudent_Payments> tblStudent_Payments { get; set; }
        public virtual DbSet<tblStudent_Registration> tblStudent_Registration { get; set; }
        public virtual DbSet<tbltopics_Contents> tbltopics_Contents { get; set; }
        public virtual DbSet<tbltraining_course_fees> tbltraining_course_fees { get; set; }
        public virtual DbSet<tbltraining_course_topics> tbltraining_course_topics { get; set; }
        public virtual DbSet<tbltraining_courses> tbltraining_courses { get; set; }
        public virtual DbSet<tbltraining_topics> tbltraining_topics { get; set; }
    }
}
