//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem_DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudent_details()
        {
            this.tblStudent_Registration = new HashSet<tblStudent_Registration>();
        }
    
        public int Student_id { get; set; }
        public string Student_name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string qualification { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudent_Registration> tblStudent_Registration { get; set; }
    }
}
