//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem_DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent_Payments
    {
        public int Payment_id { get; set; }
        public Nullable<int> registration_id { get; set; }
        public Nullable<System.DateTime> Payment_date { get; set; }
        public Nullable<double> Payment_amount { get; set; }
        public string Payment_mode { get; set; }
        public string Payment_description { get; set; }
    
        public virtual tblStudent_Registration tblStudent_Registration { get; set; }
    }
}
