//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPSystem_DatabaseOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudent_Registration()
        {
            this.tblStudent_Payments = new HashSet<tblStudent_Payments>();
        }
    
        public int registration_id { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<int> fee_id { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public Nullable<double> discount { get; set; }
    
        public virtual tblStudent_details tblStudent_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudent_Payments> tblStudent_Payments { get; set; }
        public virtual tbltraining_course_fees tbltraining_course_fees { get; set; }
    }
}
